# Generated by Django 5.2.9 on 2025-12-17 14:55

from django.contrib.gis.geos import GEOSGeometry
from django.db import migrations


def seed_area_imovel(apps, schema_editor):
    AreaImovel = apps.get_model("core", "AreaImovel")

    # Data provided by user
    # Mapping assumed:
    # gid=1 (not provided in value list but needed for PK)
    # cod_tema="AREA_IMOVEL"
    # nom_tema="Area do Imovel"
    # cod_imovel="SP-3500105-279714F410E746B0B440EFAD4B0933D4"
    # mod_fiscal=0.1912...
    # mod_area=3.8239...
    # ind_status="AT"
    # ind_tipo="IRU"
    # desc_condic="Aguardando analise"
    # municipio="Adamantina"
    # cod_estado="SP"
    # dat_criaca="09/10/2025"
    # dat_atuali="09/10/2025"
    # geom=HEX

    data = {
        "gid": 1,
        "cod_tema": "AREA_IMOVEL",
        "nom_tema": "Area do Imovel",
        "cod_imovel": "SP-3500105-279714F410E746B0B440EFAD4B0933D4",
        "mod_fiscal": 0.1912000000000000000000000000000,
        "mod_area": 3.8239000000000000000000000000000,
        "ind_status": "AT",
        "ind_tipo": "IRU",
        "desc_condic": "Aguardando analise",
        "municipio": "Adamantina",
        "cod_estado": "SP",
        "dat_criaca": "09/10/2025",
        "dat_atuali": "09/10/2025",
        "geom": "01060000000100000001030000000100000005000000C31064927D8949C0CB9FFC8477B535C0AE3EDC16468949C0EDDB0ED946B535C0210A74E22E8949C005C50562B0B535C0874A70B06A8949C089DCECB8E2B535C0C31064927D8949C0CB9FFC8477B535C0",
    }

    AreaImovel.objects.create(**data)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_areaimovel"),
    ]

    operations = [
        migrations.RunPython(seed_area_imovel),
    ]
