# Generated by Django CA-Antigravity

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AreaImovel",
            fields=[
                ("gid", models.IntegerField(primary_key=True, serialize=False)),
                ("cod_tema", models.CharField(blank=True, max_length=254, null=True)),
                ("nom_tema", models.CharField(blank=True, max_length=254, null=True)),
                ("cod_imovel", models.CharField(blank=True, max_length=254, null=True)),
                ("mod_fiscal", models.CharField(blank=True, max_length=254, null=True)),
                ("num_area", models.CharField(blank=True, max_length=254, null=True)),
                ("ind_status", models.CharField(blank=True, max_length=254, null=True)),
                ("ind_tipo", models.CharField(blank=True, max_length=254, null=True)),
                ("des_condic", models.CharField(blank=True, max_length=254, null=True)),
                ("municipio", models.CharField(blank=True, max_length=254, null=True)),
                ("cod_estado", models.CharField(blank=True, max_length=254, null=True)),
                ("dat_criaca", models.CharField(blank=True, max_length=254, null=True)),
                ("dat_atuali", models.CharField(blank=True, max_length=254, null=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
            ],
            options={
                "db_table": "area_imovel_1",
            },
        ),
    ]
