# Generated by Django 5.2.9 on 2025-12-17 14:55

from django.db import migrations


def seed_area_imovel(apps, schema_editor):
    pass  # No-op


def reverse_seed_area_imovel(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("fazendas", "0002_areaimovel"),
    ]

    operations = [
        migrations.RunPython(seed_area_imovel, reverse_seed_area_imovel),
    ]
