# Generated by Django 5.2.9 on 2025-12-19 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fazendas', '0005_alter_areaimovel_mod_fiscal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
