# Generated by Django 5.2.9 on 2025-12-19 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_squashed_schema_and_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areaimovel',
            name='mod_fiscal',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
